package com.model;

// Generated 8 mars 2016 22:11:39 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Agentdevise generated by hbm2java
 */
@Entity
@Table(name = "agentdevise", catalog = "echangedevise")
public class Agentdevise implements java.io.Serializable {

	private int ncin;
	private String nom;
	private String prenom;
	private String password;
	private Integer age;
	private String email;
	private Integer tel;

	public Agentdevise() {
	}

	public Agentdevise(int ncin, String nom, String prenom) {
		this.ncin = ncin;
		this.nom = nom;
		this.prenom = prenom;
	}

	public Agentdevise(int ncin, String nom, String prenom, String password,
			Integer age, String email, Integer tel) {
		this.ncin = ncin;
		this.nom = nom;
		this.prenom = prenom;
		this.password = password;
		this.age = age;
		this.email = email;
		this.tel = tel;
	}

	@Id
	@Column(name = "Ncin", unique = true, nullable = false)
	public int getNcin() {
		return this.ncin;
	}

	public void setNcin(int ncin) {
		this.ncin = ncin;
	}

	@Column(name = "nom", nullable = false, length = 70)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", nullable = false, length = 70)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "password", length = 70)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "email", length = 200)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "tel")
	public Integer getTel() {
		return this.tel;
	}

	public void setTel(Integer tel) {
		this.tel = tel;
	}

}
