package com.model;

// Generated 31 août 2016 17:16:44 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Groupecontact generated by hbm2java
 */
@Entity
@Table(name = "groupecontact", catalog = "appcontactmybuild")
public class Groupecontact implements java.io.Serializable {

	private Integer idGroupe;
	private String libelleGroupe;
	private Set<Contact> contacts = new HashSet<Contact>(0);

	public Groupecontact() {
	}

	public Groupecontact(String libelleGroupe, Set<Contact> contacts) {
		this.libelleGroupe = libelleGroupe;
		this.contacts = contacts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idGroupe", unique = true, nullable = false)
	public Integer getIdGroupe() {
		return this.idGroupe;
	}

	public void setIdGroupe(Integer idGroupe) {
		this.idGroupe = idGroupe;
	}

	@Column(name = "libelleGroupe", length = 254)
	public String getLibelleGroupe() {
		return this.libelleGroupe;
	}

	public void setLibelleGroupe(String libelleGroupe) {
		this.libelleGroupe = libelleGroupe;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "groupecontact")
	public Set<Contact> getContacts() {
		return this.contacts;
	}

	public void setContacts(Set<Contact> contacts) {
		this.contacts = contacts;
	}

}
