package com.model;

// Generated 9 oct. 2016 13:55:49 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Groupecontact generated by hbm2java
 */
@Entity
@Table(name = "groupecontact", catalog = "appcontact")
public class Groupecontact implements java.io.Serializable {

	private Integer idGroupe;
	private String libelleGroupe;
	private Set<Morale> morales = new HashSet<Morale>(0);
	private Set<Physique> physiques = new HashSet<Physique>(0);

	public Groupecontact() {
	}

	public Groupecontact(String libelleGroupe, Set<Morale> morales,
			Set<Physique> physiques) {
		this.libelleGroupe = libelleGroupe;
		this.morales = morales;
		this.physiques = physiques;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idGroupe", unique = true, nullable = false)
	public Integer getIdGroupe() {
		return this.idGroupe;
	}

	public void setIdGroupe(Integer idGroupe) {
		this.idGroupe = idGroupe;
	}

	@Column(name = "libelleGroupe", length = 254)
	public String getLibelleGroupe() {
		return this.libelleGroupe;
	}

	public void setLibelleGroupe(String libelleGroupe) {
		this.libelleGroupe = libelleGroupe;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "groupecontact")
	public Set<Morale> getMorales() {
		return this.morales;
	}

	public void setMorales(Set<Morale> morales) {
		this.morales = morales;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "groupecontact")
	public Set<Physique> getPhysiques() {
		return this.physiques;
	}

	public void setPhysiques(Set<Physique> physiques) {
		this.physiques = physiques;
	}

	
	
	
	  @Override
	    public boolean equals(Object other) {
	        return (other instanceof Groupecontact) && (idGroupe != null)
	            ? idGroupe.equals(((Groupecontact) other).idGroupe)
	            : (other == this);
	    }

	    @Override
	    public int hashCode() {
	        return (idGroupe != null)
	            ? (this.getClass().hashCode() + idGroupe.hashCode())
	            : super.hashCode();
	    }

	    @Override
	    public String toString() {
	        return String.format("Groupecontact[%d, %s]", idGroupe,libelleGroupe);
	    }
	
}
