package com.model;

// Generated 31 août 2016 17:16:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Membre generated by hbm2java
 */
@Entity
@Table(name = "membre", catalog = "appcontactmybuild")
public class Membre implements java.io.Serializable {

	private Integer idmembre;
	private Fonction fonction;
	private Morale morale;
	private String nom;
	private String prenom;
	private String adresse;
	private String email;
	private Integer telephone;

	public Membre() {
	}

	public Membre(Fonction fonction, Morale morale, String nom, String prenom,
			String adresse, String email, Integer telephone) {
		this.fonction = fonction;
		this.morale = morale;
		this.nom = nom;
		this.prenom = prenom;
		this.adresse = adresse;
		this.email = email;
		this.telephone = telephone;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "iDMembre", unique = true, nullable = false)
	public Integer getIdmembre() {
		return this.idmembre;
	}

	public void setIdmembre(Integer idmembre) {
		this.idmembre = idmembre;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idFonction",nullable = true)
	public Fonction getFonction() {
		return this.fonction;
	}

	public void setFonction(Fonction fonction) {
		this.fonction = fonction;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idContact",nullable = false)
	public Morale getMorale() {
		return this.morale;
	}

	public void setMorale(Morale morale) {
		this.morale = morale;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 254)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "adresse", length = 254)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "email", length = 254)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telephone")
	public Integer getTelephone() {
		return this.telephone;
	}

	public void setTelephone(Integer telephone) {
		this.telephone = telephone;
	}

}
