package com.model;

// Generated 9 oct. 2016 13:55:49 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Membre generated by hbm2java
 */
@Entity
@Table(name = "membre", catalog = "appcontact")
public class Membre implements java.io.Serializable {

	private Integer idmembre;
	private Morale morale;
	private Fonction fonction;
	private String nom;
	private String prenom;
	private String adresse;
	private String email;
	private String telephone;
	private Date date;
	private Date datetime;

	public Membre() {
	}

	public Membre(Morale morale, Fonction fonction, String nom, String prenom,
			String adresse, String email, String telephone, Date date,
			Date datetime) {
		this.morale = morale;
		this.fonction = fonction;
		this.nom = nom;
		this.prenom = prenom;
		this.adresse = adresse;
		this.email = email;
		this.telephone = telephone;
		this.date = date;
		this.datetime = datetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "iDMembre", unique = true, nullable = false)
	public Integer getIdmembre() {
		return this.idmembre;
	}

	public void setIdmembre(Integer idmembre) {
		this.idmembre = idmembre;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idMorale")
	public Morale getMorale() {
		return this.morale;
	}

	public void setMorale(Morale morale) {
		this.morale = morale;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idFonction")
	public Fonction getFonction() {
		return this.fonction;
	}

	public void setFonction(Fonction fonction) {
		this.fonction = fonction;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 254)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "adresse", length = 254)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "email", length = 254)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telephone")
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datetime", length = 19)
	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

}
