package com.model;

// Generated 31 août 2016 17:16:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Physique generated by hbm2java
 */
@Entity
@Table(name = "physique", catalog = "appcontactmybuild")
public class Physique implements java.io.Serializable {

	private Integer idContact;
	private Contact contact;
	private String prenom;
	private String age;
	private String fonction;
	private String civilite;

	public Physique() {
	}

	public Physique(Contact contact) {
		this.contact = contact;
	}

	public Physique(Contact contact, String prenom, String age,
			String fonction, String civilite) {
		this.contact = contact;
		this.prenom = prenom;
		this.age = age;
		this.fonction = fonction;
		this.civilite = civilite;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "contact"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "idContact", unique = true, nullable = false)
	public Integer getIdContact() {
		return this.idContact;
	}

	public void setIdContact(Integer idContact) {
		this.idContact = idContact;
	}

	@OneToOne(fetch = FetchType.EAGER)
	@PrimaryKeyJoinColumn
	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	@Column(name = "prenom", length = 254)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "age", length = 254)
	public String getAge() {
		return this.age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	@Column(name = "fonction", length = 254)
	public String getFonction() {
		return this.fonction;
	}

	public void setFonction(String fonction) {
		this.fonction = fonction;
	}

	@Column(name = "civilite", length = 254)
	public String getCivilite() {
		return this.civilite;
	}

	public void setCivilite(String civilite) {
		this.civilite = civilite;
	}

}
