package com.model;

// Generated 31 août 2016 17:16:44 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name = "region", catalog = "appcontactmybuild")
public class Region implements java.io.Serializable {

	private Integer idRegion;
	private String libelleRegion;
	private Set<Contact> contacts = new HashSet<Contact>(0);

	public Region() {
	}

	public Region(String libelleRegion, Set<Contact> contacts) {
		this.libelleRegion = libelleRegion;
		this.contacts = contacts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idRegion", unique = true, nullable = false)
	public Integer getIdRegion() {
		return this.idRegion;
	}

	public void setIdRegion(Integer idRegion) {
		this.idRegion = idRegion;
	}

	@Column(name = "libelleRegion", length = 254)
	public String getLibelleRegion() {
		return this.libelleRegion;
	}

	public void setLibelleRegion(String libelleRegion) {
		this.libelleRegion = libelleRegion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
	public Set<Contact> getContacts() {
		return this.contacts;
	}

	public void setContacts(Set<Contact> contacts) {
		this.contacts = contacts;
	}

}
