package com.model;

// Generated 31 août 2016 17:16:44 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Secteur generated by hbm2java
 */
@Entity
@Table(name = "secteur", catalog = "appcontactmybuild")
public class Secteur implements java.io.Serializable {

	private Integer idSecteur;
	private String libelleSecteur;
	private Set<Contact> contacts = new HashSet<Contact>(0);

	public Secteur() {
	}

	public Secteur(String libelleSecteur, Set<Contact> contacts) {
		this.libelleSecteur = libelleSecteur;
		this.contacts = contacts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idSecteur", unique = true, nullable = false)
	public Integer getIdSecteur() {
		return this.idSecteur;
	}

	public void setIdSecteur(Integer idSecteur) {
		this.idSecteur = idSecteur;
	}

	@Column(name = "libelleSecteur", length = 254)
	public String getLibelleSecteur() {
		return this.libelleSecteur;
	}

	public void setLibelleSecteur(String libelleSecteur) {
		this.libelleSecteur = libelleSecteur;
	}
	
//	@Override
//  public String toString() {
//      return libelleSecteur;
//  }

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "secteur")
	public Set<Contact> getContacts() {
		return this.contacts;
	}

	public void setContacts(Set<Contact> contacts) {
		this.contacts = contacts;
	}
	

	


}
