package com.model;

// Generated 9 oct. 2016 13:55:49 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Typemoral generated by hbm2java
 */
@Entity
@Table(name = "typemoral", catalog = "appcontact")
public class Typemoral implements java.io.Serializable {

	private Integer idTypeMoral;
	private String libelleMorale;
	private Set<Morale> morales = new HashSet<Morale>(0);

	public Typemoral() {
	}

	public Typemoral(String libelleMorale, Set<Morale> morales) {
		this.libelleMorale = libelleMorale;
		this.morales = morales;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idTypeMoral", unique = true, nullable = false)
	public Integer getIdTypeMoral() {
		return this.idTypeMoral;
	}

	public void setIdTypeMoral(Integer idTypeMoral) {
		this.idTypeMoral = idTypeMoral;
	}

	@Column(name = "libelleMorale", length = 254)
	public String getLibelleMorale() {
		return this.libelleMorale;
	}

	public void setLibelleMorale(String libelleMorale) {
		this.libelleMorale = libelleMorale;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "typemoral")
	public Set<Morale> getMorales() {
		return this.morales;
	}

	public void setMorales(Set<Morale> morales) {
		this.morales = morales;
	}
	
	  @Override
	    public boolean equals(Object other) {
	        return (other instanceof Typemoral) && (idTypeMoral != null)
	            ? idTypeMoral.equals(((Typemoral) other).idTypeMoral)
	            : (other == this);
	    }

	    @Override
	    public int hashCode() {
	        return (idTypeMoral != null)
	            ? (this.getClass().hashCode() + idTypeMoral.hashCode())
	            : super.hashCode();
	    }

	    @Override
	    public String toString() {
	        return String.format("TyepeMoral[%d, %s]", idTypeMoral,libelleMorale);
	    }

}
